/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import datos.EjemplarData;
import datos.LibroData;
import entidades.Ejemplar;
import entidades.Libro;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author conandoel
 */
public class AgregarEjemplarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarEjemplarView
     */
    List<Libro> libros=new ArrayList<>();
    public AgregarEjemplarView() {
        initComponents();
        cargarcbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbLibros = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcbEditoriales = new javax.swing.JComboBox<>();

        jLabel1.setText("Libro:");

        jLabel2.setText("Agregar Ejemplar");

        jcbLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLibrosActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Editorial:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbEditoriales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jcbLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbEditoriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EjemplarData ed=new EjemplarData();
        Ejemplar ejemplar=new Ejemplar();
        for(Libro libro:libros){
            if(libro.getTitulo().equals(jcbLibros.getSelectedItem().toString()) && libro.getEditorial().equals(jcbEditoriales.getSelectedItem().toString())){
                ejemplar.setEstado("Disponible");
                ejemplar.setLibro(libro);
                ed.agregarEjemplar(ejemplar);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLibrosActionPerformed
        // TODO add your handling code here:
        limpiarEditoriales();
        for(Libro libro:libros){
            if(libro.getTitulo().equals(jcbLibros.getSelectedItem().toString())){
                jcbEditoriales.addItem(libro.getEditorial());
            }
        }
    }//GEN-LAST:event_jcbLibrosActionPerformed

    private void cargarcbl(){
        LibroData ld=new LibroData();
        libros=ld.listarLibroSinAutor();
        for(Libro libro:libros){
            jcbLibros.addItem(libro.getTitulo());
        }
    }
    private void limpiarEditoriales(){
        int j=jcbEditoriales.getItemCount();
        if(j>0){
        try{
            for(int i=j-1;i>=0;i--){
                jcbEditoriales.removeItemAt(i);
            }
        }catch(NullPointerException ex){
        
        }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jcbEditoriales;
    private javax.swing.JComboBox<String> jcbLibros;
    // End of variables declaration//GEN-END:variables
}
