/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import datos.PrestamoData;
import datos.SocioData;
import entidades.Prestamo;
import entidades.Socio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author conandoel
 */
public class DevolucionesView extends javax.swing.JInternalFrame {

    /**
     * Creates new form DevolucionesView
     */
        List<Socio> socios=new ArrayList<>();
        List<Prestamo> prestamos=new ArrayList<>();
        
        private DefaultTableModel modelo=new DefaultTableModel();

    public DevolucionesView() {
        initComponents();
        cargarSocios();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfIdSocio = new javax.swing.JTextField();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlDireccion = new javax.swing.JLabel();
        jlMail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDevoluciones = new javax.swing.JTable();
        jbtDevolver = new javax.swing.JToggleButton();

        jLabel1.setText("Lector:");

        jtfIdSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfIdSocioKeyReleased(evt);
            }
        });

        jlNombre.setText("Nombre: ");

        jlApellido.setText("Apellido:");

        jlDireccion.setText("Direccion:");

        jlMail.setText("E-Mail:");

        jLabel2.setText("Devolucion");

        jtbDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbDevoluciones);

        jbtDevolver.setText("Devolver");
        jbtDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlDireccion)
                                .addGap(18, 18, 18)
                                .addComponent(jlMail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jtfIdSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlNombre)
                                .addGap(18, 18, 18)
                                .addComponent(jlApellido))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel2)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtDevolver)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jlNombre)
                    .addComponent(jlApellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDireccion)
                    .addComponent(jlMail))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtDevolver)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIdSocioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdSocioKeyReleased
        // TODO add your handling code here:
        limpiarLabels();
        limpiarTabla();
        if(jtfIdSocio.getText().equals("")){limpiarLabels();
            limpiarTabla();
        }else{
            for(Socio socio:socios){
                if(String.valueOf(socio.getIdSocio()).equals(jtfIdSocio.getText())){
                    jlApellido.setText("Apellido: "+socio.getApellido());
                    jlNombre.setText("Nombre: "+socio.getNombre());
                    jlDireccion.setText("Direccion: "+socio.getDomicilio());
                    jlMail.setText("E-Mail: "+socio.getMail());
                    cargarDev(socio);
                }
            }
        }
    }//GEN-LAST:event_jtfIdSocioKeyReleased

    private void jbtDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDevolverActionPerformed
        // TODO add your handling code here:
        
        if(jtbDevoluciones.getSelectedRow()>-1){
            int idej=jtbDevoluciones.getSelectedRow();
            int cel=Integer.parseInt(jtbDevoluciones.getValueAt(idej, 0).toString());
            PrestamoData pd=new PrestamoData();
            pd.devolucionPrestamo(cel);
            Socio socio=new Socio();
            socio.setIdSocio(Integer.parseInt(jtfIdSocio.getText()));
            limpiarTabla();
            cargarDev(socio);
        }else{JOptionPane.showMessageDialog(null, "Debe elegir un prestamo de la tabla");}
    }//GEN-LAST:event_jbtDevolverActionPerformed

    private void limpiarLabels(){
        jlApellido.setText("Apellido: ");
                jlNombre.setText("Nombre: ");
                jlDireccion.setText("Direccion: ");
                jlMail.setText("E-Mail: ");
    }
    private void cargarSocios(){
        SocioData sd= new SocioData();
        socios=sd.buscarHistorialSocios("Estado", "1");
    }
    
    private void cargarTabla(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Socio");
        modelo.addColumn("Ejemplar");
        modelo.addColumn("Fecha Pres.");
        modelo.addColumn("Fecha Dev.");
        jtbDevoluciones.setModel(modelo);
    }
    private void limpiarTabla(){
        int f=modelo.getRowCount()-1;
        for(;f>=0;f--){
            modelo.removeRow(f);
        }
    }
    
    private void cargarDev(Socio socio){
        PrestamoData pd=new PrestamoData();
        prestamos=null;
        prestamos=pd.listarPrestamosSuperCargado(socio.getIdSocio());
        cargarTablaDev();
    }
    
    private void cargarTablaDev(){
        for(Prestamo prestamo:prestamos){
            modelo.addRow(new Object[]{prestamo.getIdPrestamo(),prestamo.getLector().getIdSocio(),prestamo.getEjemplar().getLibro().getTitulo(),prestamo.getFechaInicio(),prestamo.getFechaFin()});
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jbtDevolver;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlMail;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JTable jtbDevoluciones;
    private javax.swing.JTextField jtfIdSocio;
    // End of variables declaration//GEN-END:variables
}
