/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import datos.EjemplarData;
import entidades.Ejemplar;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author conandoel
 */
public class ModificarEjemplarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarEjemplarView
     */
    List<Ejemplar> ejemplares=new ArrayList<>();
    
    public ModificarEjemplarView() {
        initComponents();
        cargarEjemplares();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfIdEjemplar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfLibro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbEstados = new javax.swing.JComboBox<>();
        jbtnModificar = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Ejemplar:");

        jtfIdEjemplar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfIdEjemplarKeyReleased(evt);
            }
        });

        jLabel2.setText("Libro:");

        jLabel3.setText("Estado:");

        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        jLabel4.setText("Modificar Ejemplar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnModificar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfIdEjemplar)
                                .addComponent(jtfLibro)
                                .addComponent(jcbEstados, 0, 156, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel4)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfIdEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnModificar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIdEjemplarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdEjemplarKeyReleased
        // TODO add your handling code here:
        
        if(jtfIdEjemplar.getText().equals("")){
            
        }else{
            for(Ejemplar ejemplar:ejemplares){
                if(String.valueOf(ejemplar.getCodigo()).equals(jtfIdEjemplar.getText())){
                    jtfLibro.setText(ejemplar.getLibro().getTitulo());
                    jcbEstados.setSelectedItem(ejemplar.getEstado());
                    jtfLibro.setEditable(false);
                }
            }
        }
    }//GEN-LAST:event_jtfIdEjemplarKeyReleased

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        // TODO add your handling code here:
        EjemplarData ed=new EjemplarData();
        Ejemplar ejemplar =new Ejemplar();
        ejemplar.setCodigo(Integer.parseInt(jtfIdEjemplar.getText()));
        ejemplar.setEstado(jcbEstados.getSelectedItem().toString());
        ed.modificarEjemplar(ejemplar);
        cargarEjemplares();
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void cargarEjemplares(){
        EjemplarData ed=new EjemplarData();
        ejemplares=ed.listarEjemplaresLibre();
    }
    
    private void cargarCombo(){
        jcbEstados.addItem("Disponible");
        jcbEstados.addItem("Prestado");
        jcbEstados.addItem("En Reparación");
        jcbEstados.addItem("Con Demora");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jbtnModificar;
    private javax.swing.JComboBox<String> jcbEstados;
    private javax.swing.JTextField jtfIdEjemplar;
    private javax.swing.JTextField jtfLibro;
    // End of variables declaration//GEN-END:variables
}
