package vistas;

import datos.SocioData;
import entidades.Foto;
import entidades.Socio;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.lang.reflect.Field;
import java.awt.Color;

public class SocioAgregarView extends javax.swing.JInternalFrame {

    private static SocioAgregarView sar;
    SocioData metodoDeSocio = new SocioData();
    private Foto foto;
    
    public SocioAgregarView() {
        initComponents();
        establecerDefault();
        
        sar = this;
    }
    
    public JLabel getLabelInformativo(){
        return this.labelInformativo;
    }
  
    
     public static SocioAgregarView getInstance() {
        //Si el atributo sbr es nulo, lo creamos con el constructor
        if (sar == null) {
            sar = new SocioAgregarView();
        }
        //Se devuelve el atributo sbr
        return sar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPSocioAgregar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLApellido = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLDomicilio = new javax.swing.JLabel();
        jLDni = new javax.swing.JLabel();
        jLImagen = new javax.swing.JLabel();
        jLNumSocio = new javax.swing.JLabel();
        jLEst = new javax.swing.JLabel();
        jLNumeroDeSocio = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jTFApellido = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jTFDomicilio = new javax.swing.JTextField();
        jTFDNI = new javax.swing.JTextField();
        jLAgregar = new javax.swing.JLabel();
        jLReset = new javax.swing.JLabel();
        jLCancelar = new javax.swing.JLabel();
        jLFechaDeAlta = new javax.swing.JLabel();
        jLFechaDeBaja = new javax.swing.JLabel();
        jLAgregarSocios = new javax.swing.JLabel();
        jLTelefono = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jLMail = new javax.swing.JLabel();
        jTFMail = new javax.swing.JTextField();
        jLFechaDeAltaDEFAULT = new javax.swing.JLabel();
        jLFechaDeBajaDEFAULT = new javax.swing.JLabel();
        labelInformativo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPSocioAgregarLayout = new javax.swing.GroupLayout(jPSocioAgregar);
        jPSocioAgregar.setLayout(jPSocioAgregarLayout);
        jPSocioAgregarLayout.setHorizontalGroup(
            jPSocioAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPSocioAgregarLayout.setVerticalGroup(
            jPSocioAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        jLApellido.setText("Apellido:");

        jLNombre.setText("Nombre:");

        jLDomicilio.setText("Domicilio:");

        jLDni.setText("DNI:");

        jLImagen.setText("Imagen");
        jLImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLImagenMouseClicked(evt);
            }
        });

        jLNumSocio.setText("Socio número:");

        jLEst.setText("Estado:");

        jLNumeroDeSocio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLEstado.setForeground(java.awt.Color.green);
        jLEstado.setText("Socio Activo");

        jTFApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFApellidoActionPerformed(evt);
            }
        });
        jTFApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFApellidoKeyReleased(evt);
            }
        });

        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        jTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNombreKeyReleased(evt);
            }
        });

        jTFDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDomicilioActionPerformed(evt);
            }
        });
        jTFDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFDomicilioKeyReleased(evt);
            }
        });

        jTFDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDNIActionPerformed(evt);
            }
        });
        jTFDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFDNIKeyReleased(evt);
            }
        });

        jLAgregar.setText("Agregar");
        jLAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAgregarMouseClicked(evt);
            }
        });
        jLAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLAgregarKeyReleased(evt);
            }
        });

        jLReset.setText("Reset");

        jLCancelar.setText("Cancelar");

        jLFechaDeAlta.setText("Fecha de Alta:");

        jLFechaDeBaja.setText("Fecha de Baja:");

        jLAgregarSocios.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLAgregarSocios.setForeground(new java.awt.Color(0, 160, 210));
        jLAgregarSocios.setText("Agregar socios");

        jLTelefono.setText("Teléfono:");

        jTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTelefonoActionPerformed(evt);
            }
        });
        jTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFTelefonoKeyReleased(evt);
            }
        });

        jLMail.setText("E-Mail:");

        jTFMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFMailActionPerformed(evt);
            }
        });
        jTFMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFMailKeyReleased(evt);
            }
        });

        jLFechaDeAltaDEFAULT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLFechaDeBajaDEFAULT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLNumSocio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNombre)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLNumeroDeSocio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNombre)
                                    .addComponent(jTFApellido)
                                    .addComponent(labelInformativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDni)
                                    .addComponent(jLDomicilio)
                                    .addComponent(jLTelefono))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                    .addComponent(jTFMail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLFechaDeBajaDEFAULT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                            .addComponent(jLFechaDeAltaDEFAULT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(47, 47, 47))
                                    .addComponent(jTFDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFTelefono))))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLMail)
                            .addComponent(jLFechaDeAlta)
                            .addComponent(jLFechaDeBaja))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLEst)
                        .addGap(111, 111, 111)
                        .addComponent(jLEstado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLAgregarSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267)
                        .addComponent(jLReset, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNumSocio)
                            .addComponent(jLNumeroDeSocio)
                            .addComponent(labelInformativo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLApellido)
                            .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombre)
                            .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDomicilio)
                            .addComponent(jTFDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTelefono)
                            .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLMail)
                            .addComponent(jTFMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFechaDeAlta)
                            .addComponent(jLFechaDeAltaDEFAULT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFechaDeBaja)
                            .addComponent(jLFechaDeBajaDEFAULT))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstado)
                    .addComponent(jLEst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLReset, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLAgregarSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPSocioAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPSocioAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDNIActionPerformed
        // TODO add your handling code here:
        String caracteresIngresados = this.jTFDNI.getText();
        JTextField valoresModificados = this.jTFDNI;
        JLabel valorMod = new JLabel();
        String valorDelCampo = caracteresIngresados;
        String campo = this.jTFDNI.getText();
        
        SocioTarjeta.getInstance().cotejarDNI(caracteresIngresados, labelInformativo, valorMod, valoresModificados, 
            valorDelCampo, campo);
    }//GEN-LAST:event_jTFDNIActionPerformed

    private void jTFDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDomicilioActionPerformed
        // TODO add your handling code here:
        String caracteresIngresados = this.jTFDomicilio.getText();
        JTextField valoresModificados = this.jTFDomicilio;
        JLabel valorMod = new JLabel();
        String valorDelCampo = caracteresIngresados;
        String campo = this.jTFDomicilio.getText();
        
        SocioTarjeta.getInstance().cotejarDomicilio(caracteresIngresados, labelInformativo, valorMod, valoresModificados, 
            valorDelCampo, campo);
    }//GEN-LAST:event_jTFDomicilioActionPerformed

    private void jLAgregarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLAgregarKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jLAgregarKeyReleased

    private void jTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTelefonoActionPerformed
        // TODO add your handling code here:
        String caracteresIngresados = this.jTFTelefono.getText();
        JTextField valoresModificados = this.jTFTelefono;
        JLabel valorMod = new JLabel();
        String valorDelCampo = caracteresIngresados;
        String campo = this.jTFTelefono.getText();
        
        SocioTarjeta.getInstance().cotejarTelefono(caracteresIngresados, labelInformativo, valorMod, valoresModificados, 
            valorDelCampo, campo);
    }//GEN-LAST:event_jTFTelefonoActionPerformed

    private void jLImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLImagenMouseClicked
        // TODO add your handling code here:
        SocioData metodoDeSocio = new SocioData();
        int idSocio = metodoDeSocio.obtenerCantidadSocios() + 5556;
        this.foto = SocioTarjeta.getInstance().editarCamposSocio("Imagen", this.jLNumeroDeSocio, this.jLImagen);
    }//GEN-LAST:event_jLImagenMouseClicked
    
    private void establecerDefault(){
        Principal.getInstance().habilitarModificaciones(false, false, false);
        
        int idSocio = metodoDeSocio.obtenerCantidadSocios() + 5556;
        this.jLNumeroDeSocio.setText(String.valueOf(idSocio));
        
        DateTimeFormatter formatoDate = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        DateTimeFormatter formatoDEFAULT = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        
        LocalDate fechaDeAlta = LocalDate.now();
        LocalDate fechaDeBaja = LocalDate.now().plusYears(5);
        
        String fechaDeAltaDEFAULT = formatoDEFAULT.format(fechaDeAlta);
        String fechaDeBajaDEFAULT = formatoDEFAULT.format(fechaDeBaja);
        this.jLFechaDeAltaDEFAULT.setText(fechaDeAltaDEFAULT.replaceAll("-", " \\| "));
        this.jLFechaDeBajaDEFAULT.setText(fechaDeBajaDEFAULT.replaceAll("-", " \\| "));
    }
    
    private void jLAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAgregarMouseClicked
        // TODO add your handling code here:
        
        
        try{
        Socio socio;
        int idSocio = metodoDeSocio.obtenerCantidadSocios() + 5556; //Ese 5556 hacer método para obtener el valor más bajo de id
        String apellido = this.jTFApellido.getText();
        String nombre = this.jTFNombre.getText();
        String domicilio = this.jTFDomicilio.getText();
        int dni = Integer.parseInt(this.jTFDNI.getText());
        
        String telefono = this.jTFTelefono.getText();
        
        String mail = this.jTFMail.getText();
        
        DateTimeFormatter formatoDate = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        DateTimeFormatter formatoDEFAULT = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        
        LocalDate fechaDeAlta = LocalDate.now();
        LocalDate fechaDeBaja = LocalDate.now().plusYears(5);
        
        String fechaDeAltaDEFAULT = formatoDEFAULT.format(fechaDeAlta);
        String fechaDeBajaDEFAULT = formatoDEFAULT.format(fechaDeBaja);

        
        String ruta = "./src/vistas/imagenes/foto_" + String.valueOf(idSocio);
        String fotoNombrePerfil = ruta;
        
        boolean estado = jLEstado.getText().equals("Socio Activo");

        socio = new Socio(idSocio, apellido, nombre, domicilio, dni, telefono, mail, fechaDeAlta, fechaDeBaja, fotoNombrePerfil, estado);
        
        Class<?> clase = socio.getClass();
        
        Field[] atributos = clase.getDeclaredFields();
        
        try{
            for(Field atributo : atributos){
                atributo.setAccessible(true);
            
                Object valor = atributo.get(socio);
               /* switch(atributo.getName() == "idSocio"){
                    JOptionPane.showMessageDialog(this, "HOLA");*/
                }
               /*switch(atributo.getName() == "idSocio"){
                    JOptionPane.showMessageDialog(this, "HOLA");
                }*/
                JOptionPane.showMessageDialog(this, valor);
            }
        }catch(IllegalAccessException e){
            JOptionPane.showMessageDialog(this, "Se pudrió todo iterando en el objeto socio para ver si están todos los campos llenos");
        }
        
        
        }catch(NumberFormatException ex){
            labelInformativo.setText("Debes ingresar el DNI");
            labelInformativo.setForeground(Color.red);
            SocioTarjeta.getInstance().temporizar(labelInformativo);
        }
        
        //metodoDeSocio.agregarSocio(socio, this.foto);
        File file = this.foto.getFile();
        FileInputStream fis = this.foto.getFis();
        JOptionPane.showMessageDialog(null, this.foto.getIdSocio());
        try{
            SocioTarjeta.getInstance().saveImage(file, fis, this.foto);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Adiviná qué... Algo pasó con la imagen");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jLAgregarMouseClicked

    private void jTFApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFApellidoActionPerformed
        // TODO add your handling code here:
        String caracteresIngresados = this.jTFApellido.getText();
        JTextField valoresModificados = this.jTFApellido;
        JLabel valorMod = new JLabel();
        String valorDelCampo = caracteresIngresados;
        String campo = this.jLApellido.getText();
        
        SocioTarjeta.getInstance().cotejarApellido(caracteresIngresados, labelInformativo, valorMod, valoresModificados, 
            valorDelCampo, campo);
    }//GEN-LAST:event_jTFApellidoActionPerformed

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
        String caracteresIngresados = this.jTFNombre.getText();
        JTextField valoresModificados = this.jTFNombre;
        JLabel valorMod = new JLabel();
        String valorDelCampo = caracteresIngresados;
        String campo = this.jLNombre.getText();
        labelInformativo.setText("");
        
        SocioTarjeta.getInstance().cotejarNombre(caracteresIngresados, labelInformativo, valorMod, valoresModificados, 
            valorDelCampo, campo);
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jTFMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFMailActionPerformed
        // TODO add your handling code here:
        String caracteresIngresados = this.jTFMail.getText();
        JTextField valoresModificados = this.jTFMail;
        JLabel valorMod = new JLabel();
        String valorDelCampo = caracteresIngresados;
        String campo = this.jTFMail.getText();
        
        SocioTarjeta.getInstance().cotejarEmail(caracteresIngresados, labelInformativo, valorMod, valoresModificados, 
            valorDelCampo, campo);
    }//GEN-LAST:event_jTFMailActionPerformed

    private void jTFApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFApellidoKeyReleased
        // TODO add your handling code here:
        JLabel valorMod = new JLabel();
        
        SocioTarjeta.getInstance().noEnterApellido(labelInformativo, valorMod, evt);
    }//GEN-LAST:event_jTFApellidoKeyReleased

    private void jTFNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreKeyReleased
        // TODO add your handling code here:
        JLabel valorMod = new JLabel();
        
        SocioTarjeta.getInstance().noEnterNombre(labelInformativo, valorMod, evt);
    }//GEN-LAST:event_jTFNombreKeyReleased

    private void jTFDomicilioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDomicilioKeyReleased
        // TODO add your handling code here:
        JLabel valorMod = new JLabel();
        
        SocioTarjeta.getInstance().noEnterDomicilio(labelInformativo, valorMod, evt);
    }//GEN-LAST:event_jTFDomicilioKeyReleased

    private void jTFDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDNIKeyReleased
        // TODO add your handling code here:
        JLabel valorMod = new JLabel();
        
        SocioTarjeta.getInstance().noEnterDNI(labelInformativo, valorMod, evt);
    }//GEN-LAST:event_jTFDNIKeyReleased

    private void jTFTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTelefonoKeyReleased
        // TODO add your handling code here:
        JLabel valorMod = new JLabel();
        
        SocioTarjeta.getInstance().noEnterTelefono(labelInformativo, valorMod, evt);
    }//GEN-LAST:event_jTFTelefonoKeyReleased

    private void jTFMailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFMailKeyReleased
        // TODO add your handling code here:
        JLabel valorMod = new JLabel();
        
        SocioTarjeta.getInstance().noEnterMail(labelInformativo, valorMod, evt);
    }//GEN-LAST:event_jTFMailKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAgregar;
    private javax.swing.JLabel jLAgregarSocios;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCancelar;
    private javax.swing.JLabel jLDni;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLEst;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFechaDeAlta;
    private javax.swing.JLabel jLFechaDeAltaDEFAULT;
    private javax.swing.JLabel jLFechaDeBaja;
    private javax.swing.JLabel jLFechaDeBajaDEFAULT;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLMail;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNumSocio;
    private javax.swing.JLabel jLNumeroDeSocio;
    private javax.swing.JLabel jLReset;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JPanel jPSocioAgregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFDNI;
    private javax.swing.JTextField jTFDomicilio;
    private javax.swing.JTextField jTFMail;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JLabel labelInformativo;
    // End of variables declaration//GEN-END:variables
}
