package vistas;

import datos.SocioData;
import entidades.Foto;
import entidades.Socio;
import java.io.File;
import java.io.FileInputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;

public class SocioAgregarView extends javax.swing.JInternalFrame {

    SocioData metodoDeSocio = new SocioData();
    private Foto foto;
    
    public SocioAgregarView() {
        initComponents();
        establecerDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPSocioAgregar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLApellido = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLDomicilio = new javax.swing.JLabel();
        jLDni = new javax.swing.JLabel();
        jLImagen = new javax.swing.JLabel();
        jLNumSocio = new javax.swing.JLabel();
        jLEst = new javax.swing.JLabel();
        jLNumeroDeSocio = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jTFApellido = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jTFDomicilio = new javax.swing.JTextField();
        jTFDNI = new javax.swing.JTextField();
        jLAgregar = new javax.swing.JLabel();
        jLReset = new javax.swing.JLabel();
        jLCancelar = new javax.swing.JLabel();
        jLFechaDeAlta = new javax.swing.JLabel();
        jLFechaDeBaja = new javax.swing.JLabel();
        jLAgregarSocios = new javax.swing.JLabel();
        jLDomicilio1 = new javax.swing.JLabel();
        jTFNumeroTelefono = new javax.swing.JTextField();
        jTFCodigoArea = new javax.swing.JTextField();
        jLMail = new javax.swing.JLabel();
        jTFMail = new javax.swing.JTextField();
        jLFechaDeAltaDEFAULT = new javax.swing.JLabel();
        jLFechaDeBajaDEFAULT = new javax.swing.JLabel();

        javax.swing.GroupLayout jPSocioAgregarLayout = new javax.swing.GroupLayout(jPSocioAgregar);
        jPSocioAgregar.setLayout(jPSocioAgregarLayout);
        jPSocioAgregarLayout.setHorizontalGroup(
            jPSocioAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPSocioAgregarLayout.setVerticalGroup(
            jPSocioAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        jLApellido.setText("Apellido:");

        jLNombre.setText("Nombre:");

        jLDomicilio.setText("Domicilio:");

        jLDni.setText("DNI:");

        jLImagen.setText("Imagen");
        jLImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLImagenMouseClicked(evt);
            }
        });

        jLNumSocio.setText("Socio número:");

        jLEst.setText("Estado:");

        jLNumeroDeSocio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLEstado.setForeground(java.awt.Color.green);
        jLEstado.setText("Socio Activo");

        jTFDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDomicilioActionPerformed(evt);
            }
        });

        jTFDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDNIActionPerformed(evt);
            }
        });

        jLAgregar.setText("Agregar");
        jLAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAgregarMouseClicked(evt);
            }
        });
        jLAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLAgregarKeyReleased(evt);
            }
        });

        jLReset.setText("Reset");

        jLCancelar.setText("Cancelar");

        jLFechaDeAlta.setText("Fecha de Alta:");

        jLFechaDeBaja.setText("Fecha de Baja:");

        jLAgregarSocios.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLAgregarSocios.setForeground(new java.awt.Color(0, 160, 210));
        jLAgregarSocios.setText("Agregar socios");

        jLDomicilio1.setText("Teléfono");

        jTFNumeroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroTelefonoActionPerformed(evt);
            }
        });

        jTFCodigoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoAreaActionPerformed(evt);
            }
        });

        jLMail.setText("E-Mail");

        jLFechaDeAltaDEFAULT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLFechaDeBajaDEFAULT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLNumSocio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNombre)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLNumeroDeSocio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNombre)
                                    .addComponent(jTFApellido)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDni)
                                    .addComponent(jLDomicilio)
                                    .addComponent(jLDomicilio1))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTFMail, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTFCodigoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTFNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLFechaDeBajaDEFAULT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                        .addComponent(jLFechaDeAltaDEFAULT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLMail)
                            .addComponent(jLFechaDeAlta)
                            .addComponent(jLFechaDeBaja))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLEst)
                        .addGap(111, 111, 111)
                        .addComponent(jLEstado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLAgregarSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267)
                        .addComponent(jLReset, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNumSocio)
                            .addComponent(jLNumeroDeSocio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLApellido)
                            .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombre)
                            .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDomicilio)
                            .addComponent(jTFDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDomicilio1)
                            .addComponent(jTFNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCodigoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLMail)
                            .addComponent(jTFMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFechaDeAlta)
                            .addComponent(jLFechaDeAltaDEFAULT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFechaDeBaja)
                            .addComponent(jLFechaDeBajaDEFAULT))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstado)
                    .addComponent(jLEst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLReset, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLAgregarSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPSocioAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPSocioAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDNIActionPerformed

    private void jTFDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDomicilioActionPerformed

    private void jLAgregarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLAgregarKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jLAgregarKeyReleased

    private void jTFNumeroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroTelefonoActionPerformed

    private void jTFCodigoAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoAreaActionPerformed

    private void jLImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLImagenMouseClicked
        // TODO add your handling code here:
        SocioData metodoDeSocio = new SocioData();
        int idSocio = metodoDeSocio.obtenerCantidadSocios() + 5556;
        this.foto = SocioTarjeta.getInstance().editarCamposSocio("Imagen", this.jLNumeroDeSocio, this.jLImagen);
    }//GEN-LAST:event_jLImagenMouseClicked
    
    private void establecerDefault(){
        Principal.getInstance().cargarAgregarSocio();
        Principal.getInstance().habilitarModificaciones(false, false, false);
        
        int idSocio = metodoDeSocio.obtenerCantidadSocios() + 5556;
        this.jLNumeroDeSocio.setText(String.valueOf(idSocio));
        
        DateTimeFormatter formatoDate = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        DateTimeFormatter formatoDEFAULT = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        
        LocalDate fechaDeAlta = LocalDate.now();
        LocalDate fechaDeBaja = LocalDate.now().plusYears(5);
        
        String fechaDeAltaDEFAULT = formatoDEFAULT.format(fechaDeAlta);
        String fechaDeBajaDEFAULT = formatoDEFAULT.format(fechaDeBaja);
        this.jLFechaDeAltaDEFAULT.setText(fechaDeAltaDEFAULT.replaceAll("-/", " \\| "));
        this.jLFechaDeBajaDEFAULT.setText(fechaDeBajaDEFAULT.replaceAll("-/", " \\| "));
    }
    
    private void jLAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAgregarMouseClicked
        // TODO add your handling code here:
        
        Socio socio;
        int idSocio = metodoDeSocio.obtenerCantidadSocios() + 5556; //Ese 5556 hacer método para obtener el valor más bajo de id
        String apellido = this.jTFApellido.getText();
        String nombre = this.jTFNombre.getText();
        String domicilio = this.jTFDomicilio.getText();
        int dni = Integer.parseInt(this.jTFDNI.getText());
        
        String codigoArea = this.jTFCodigoArea.getText();
        String telefono = this.jTFNumeroTelefono.getText();
        
        String telefonoCompleto = codigoArea + telefono;
        String mail = this.jTFMail.getText();
        
        DateTimeFormatter formatoDate = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        DateTimeFormatter formatoDEFAULT = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        
        LocalDate fechaDeAlta = LocalDate.now();
        LocalDate fechaDeBaja = LocalDate.now().plusYears(5);
        
        String fechaDeAltaDEFAULT = formatoDEFAULT.format(fechaDeAlta);
        String fechaDeBajaDEFAULT = formatoDEFAULT.format(fechaDeBaja);

        
        String ruta = "./src/vistas/imagenes/foto_" + String.valueOf(idSocio);
        String fotoNombrePerfil = ruta;
        
        boolean estado = jLEstado.getText().equals("Socio Activo");

        socio = new Socio(idSocio, apellido, nombre, domicilio, dni, telefonoCompleto, mail, fechaDeAlta, fechaDeBaja, fotoNombrePerfil, estado);
        metodoDeSocio.agregarSocio(socio, this.foto);
        File file = this.foto.getFile();
        FileInputStream fis = this.foto.getFis();
        JOptionPane.showMessageDialog(null, this.foto.getIdSocio());
        try{
            SocioTarjeta.getInstance().saveImage(file, fis, this.foto);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Adiviná qué... Algo pasó con la imagen");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jLAgregarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAgregar;
    private javax.swing.JLabel jLAgregarSocios;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCancelar;
    private javax.swing.JLabel jLDni;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLDomicilio1;
    private javax.swing.JLabel jLEst;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFechaDeAlta;
    private javax.swing.JLabel jLFechaDeAltaDEFAULT;
    private javax.swing.JLabel jLFechaDeBaja;
    private javax.swing.JLabel jLFechaDeBajaDEFAULT;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLMail;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNumSocio;
    private javax.swing.JLabel jLNumeroDeSocio;
    private javax.swing.JLabel jLReset;
    private javax.swing.JPanel jPSocioAgregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFCodigoArea;
    private javax.swing.JTextField jTFDNI;
    private javax.swing.JTextField jTFDomicilio;
    private javax.swing.JTextField jTFMail;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNumeroTelefono;
    // End of variables declaration//GEN-END:variables
}
